#!/bin/bash
set +e

docker-compose down -v --remove-orphans
wait
echo '###########################'
echo 'BEGIN: docker-compose build'
echo '###########################'
docker-compose build # Set up the Docker containers
wait
echo '##############################'
echo 'FINISHED: docker-compose build'
echo '##############################'

echo '--------------------------------------------'
echo 'BEGIN: docker-compose run web rails db:reset'
echo '--------------------------------------------'
docker-compose run web rails db:reset
echo '------------------------------------------'
echo 'END: docker-compose run web rails db:reset'
echo '------------------------------------------'
